# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160504_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visit_time',
            field=models.DateTimeField(),
        ),
    ]
