# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_liuyan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liuyan',
            old_name='liuyan',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='liuyan',
            name='liuyan_time',
        ),
    ]
