# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160509_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liuyan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liuyan', models.TextField()),
                ('liuyan_time', models.DateTimeField()),
            ],
        ),
    ]
