# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160509_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='add_zan',
            field=models.IntegerField(default='1', max_length=10),
        ),
    ]
